version: 2

models:
  - name: compare_queries
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_relations_without_exclude')

  - name: compare_queries_with_summary
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_with_summary')

  - name: compare_queries_without_summary
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_without_summary')
          
  - name: compare_relations_with_exclude
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_relations_with_exclude')

  - name: compare_relations_without_exclude
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_results__compare_relations_without_exclude')
